version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "${EXTERNAL_PORT:-4480}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./uploads:/var/www/uploads
    depends_on:
      - webapp
    restart: unless-stopped

  webapp:
    build: ./app
    env_file:
      - ./app/.env
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_USER=medical_user
      - DB_NAME=medical_assistant
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    env_file:
      - ./app/.env
    environment:
      - POSTGRES_DB=medical_assistant
      - POSTGRES_USER=medical_user
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medical_user -d medical_assistant"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
